name: Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
      - name: Package Pages artifact
        run: |
          tar \
            --dereference --hard-dereference \
            --directory ./_site \
            --create --file "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            --exclude='.[^/]*' \
            .
      - name: Upload Pages artifact
        uses: actions/upload-artifact@v7
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
